if [ -f /usr/share/bash-completion/completions/git ]; then
	source /usr/share/bash-completion/completions/git
fi
if [ -f /etc/bash_completion.d/git-prompt ]; then
	source /etc/bash_completion.d/git-prompt
fi

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

export PATH=$PATH:"~/git/odds-and-ends/python":$JAVA_HOME"/bin":"C:\Program Files (x86)\GnuWin32\bin"
export EDITOR='vi'
export DISPLAY=:0.0
export PROMPT_COMMAND="printf '\n'"
export PS1="\[\e[01;32m\]\u@\h \[\e[01;34m\]\w\[\e[36m\]\$(__git_ps1)\[\e[0m\]"$'\n$ '
export BASHRC="~/git/odds-and-ends/dotfiles/bashrc"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias bup='source ~/.bashrc && test -f ~/.bash_profile && source ~/.bash_profile'
alias vib='vi ~/git/odds-and-ends/dotfiles/bashrc ~/.bashrc ~/.bashrc.custom && bup'

alias findi='find . -iname'
alias psgrep='ps aux | grep'
alias grepr='grep -ril'

alias cd..='cd ..'
alias cd-='cd -'
alias la='ls -a'
alias ll='la -lh'
alias vi='vi -p'

alias mci='mvn clean install'
alias mcis='mci -DskipTests'
alias mrun='reset && mvn spring-boot:run'
alias mwebdeploy='mvn com.oracle.weblogic:weblogic-maven-plugin:redeploy'

alias gmerge='git merge -s recursive -X renormalize'
alias stashlist='git stash list'
alias stash='git stash save -u'
alias unstash='git stash pop'
alias tree="mvn dependency:tree | vi -"
alias odds="cd ~/git/odds-and-ends"
alias mkdir="mkdir -p"
alias up="docker compose up --build -d"
alias down="docker compose down"
alias bounce="down && up"
alias weather="curl -s https://wttr.in"
alias hosts="grep host ~/.ssh/config | awk '{printf \"%s \", \$2}'; echo"
alias hostsl="cat ~/.ssh/config"

function findgrep {
	findi $1 -print0 | xargs -0 grep -i $2
}

function vigrep {
	grep -ril $1 | sed 's/ /\\ /g'
	vi `grep -ril $1 | sed 's/ /\\ /g'`
}

function vifind {
	find . -iname $1
	vi `find . -iname $1`
}
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('conda' 'shell.bash' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/home/sam/anaconda3/etc/profile.d/conda.sh" ]; then
#        . "/home/sam/anaconda3/etc/profile.d/conda.sh"
#    else
#        export PATH="/home/sam/anaconda3/bin:$PATH"
#    fi  
#fi
#unset __conda_setup

# <<< conda initialize <<<
# keep another bashrc in home directory for secret things that shouldn't/can't be committed
test -f ~/.bashrc.custom && . ~/.bashrc.custom
