#! /bin/bash

if [ $# -ne 4 ] ; then
	echo "usage: bloopbackup <userNumber> <latestEntryNumber> <username> <password>"
	exit 1
fi

echo "http://www.bloopdiary.com/viewfront.php?id=$1" >> tmpInput

for ((i=1;i<=$2;i+=1)); do
	echo "http://www.bloopdiary.com/viewentry.php?id=$1&num=$i">> tmpInput
done
wget --save-cookies cookies.txt --post-data "username=$3&password=$4" http://www.bloopdiary.com/login.php -O -
wget --load-cookies cookies.txt --convert-links --html-extension --input-file tmpInput 

rm tmpInput cookies.txt

#grep "It may have been deleted by the user, or privatised." * --files-with-matches | xargs grep -v comments --files-with-matches | xargs rm
